apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: go-app
  namespace: argocd

spec:
  project: default
  source:
    repoURL: https://github.com/in3t/go-argo-demo.git
    targetRevision: main
    path: k8s
    
  destination:
    server: https://kubernetes.default.svc
    namespace: go-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true